title:            David Leonard
description:      Describe your website here.
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://drksephy.github.io/

# Owner/author information
owner:
  name:           David Leonard
  avatar:         avatar.jpg
  bio:            Programming Wizard
  email:          DrkSephy1025@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         DrkSephy
  stackexchange:  
  bitbucket:      DrkSephy
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes

# Links to include in top navigation
# For external links add external: true
links:
  - title: Portfolio
    url: /portfolio
  - title: Tutorials
    url: /tutorials

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown


permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class