# Site settings
title: David Leonard
header-img: img/forest.jpg
email: DrkSephy1025@gmail.com
description: "Full-stack JavaScript Developer"
baseurl: ""
url: "http://drksephy.github.io"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 15
